### ISSUE TITLE
Support node 16 (update puppeteer)

### ISSUE THREAD

**Issue by rsodre** [neocotic/convert-svg#100]
I'm reusing my SVG to PNG code that is battle tested on an old (2021!) project, but when deploying to Vercel, I get this error calling the endpoint:
```
2022-12-21T02:15:00.609Z	9e2b2872-6888-4569-b0e6-0befd516db2d	ERROR	Error: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).
    at ChromeLauncher.launch (/var/task/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:105:23)
    at async Converter.[getPage] (/var/task/node_modules/convert-svg-core/src/Converter.js:364:24)
    at async Converter.[convert] (/var/task/node_modules/convert-svg-core/src/Converter.js:283:18)
    at async Converter.convert (/var/task/node_modules/convert-svg-core/src/Converter.js:185:12)
    at async API.convert (/var/task/node_modules/convert-svg-core/src/API.js:80:16)
    at async handler (/var/task/.next/server/pages/api/misc/aspng.js:50:23)
    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:185:9)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:395:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:496:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:226:36)
```

It seems like the puppeteer version used by this package works only with Node 14, not Node 16.

Some insight...
https://github.com/vercel/community/discussions/124

**Comment by nevenhsu** [comment]
Do you have any solution to this issue?
I change node to 14 in the vercel setting, but it doesn't work.

**Comment by neocotic** [comment]
Sorry for the huge delay but I've been struggling to find time to do what I wanted to with this project over the last few years.

I'm pleased to say that today I released `0.7.0` of all packages which does contain some important breaking changes. Please carefully read the [changelog](https://github.com/neocotic/convert-svg/blob/main/CHANGES.md#version-070-20250614).

Thanks for taking time to report this bug and I'm happy to say that it should be resolved in the latest version as `puppeteer` has been bumped to the latest version.
