### ISSUE TITLE
Can't run in loop quickly, fails to open chrome eventually

### ISSUE THREAD

**Issue by johnnyshankman** [neocotic/convert-svg#75]
Error:
```
(node:31891) UnhandledPromiseRejectionWarning: Error: Failed to launch chrome!


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/Users/johnshankman/Documents/rpunks/radioactive-punks/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/Users/johnshankman/Documents/rpunks/radioactive-punks/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31891) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:31891) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Setup:

Create a for loop that does this over and over again.
```
const png = await convert(someSvgString, {
    height: 500,
    width: 500
  })
```

**Comment by neocotic** [comment]
Can you try again using today's [0.6.0](https://github.com/neocotic/convert-svg/releases/tag/0.6.0) release to determine if there's any noticeable difference?

I use this library in my [brander](https://github.com/neocotic/brander) library to generate hundreds of assets consecutively and haven't experience this issue. That said; I notice that you're using the main `convert` method which creates a new instance of Chromium each time it's called. It's strongly recommended that you use `createConverter` to create a single Chromium instance but make sure you `destroy` it once you're done to free up resources (i.e. kills the orphaned Chromium instance).

For example;

``` javascript
const { createConverter } = require('convert-svg-to-png');
const { readdir } = require('fs/promises');

async function convertSvgFiles(dirPath) {
  const converter = createConverter();

  try {
    const filePaths = await readdir(dirPath);

    for (const filePath of filePaths) {
      await converter.convertFile(filePath);
    }
  } finally {
    await converter.destroy();
  }
}
```

**Comment by johnnyshankman** [comment]
@neocotic great advice! i didn't know about the `createConverter` optimization. I think that'll fix everything alone, but I'll also try the update as well. Thank you so much.

**Comment by neocotic** [comment]
Let me know how you get on and hopefully we can close this issue out 🤘
